version: '3'

services:
  glpi:
    image: diouxx/glpi
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - GLPI_DB_HOST=db
      - GLPI_DB_USER=glpi
      - GLPI_DB_PASSWORD=glpi_password
      - GLPI_DB_NAME=glpi
    volumes:
      - glpi_data:/var/www/html/files
      
  volumes:
  glpi_data:
